### ISSUE TITLE
S3Source bucket name environment variable may be wrong?

### ISSUE THREAD

**Issue by mcritchlow** [UCLALibrary/terraform-kubernetes-cantaloupe#2]
Hi there,

@ksclarke pointed me here as I'm looking to [create a Helm chart](https://gitlab.com/surfliner/surfliner/-/merge_requests/783) for Project Surfliner based off the excellent work you all have done on the canteloupe container image as well as this terraform configuration for deploying to k8s.

I wanted to make a quick note that I _think_ the following environment variable referenced here: https://github.com/UCLALibrary/terraform-kubernetes-cantaloupe/blob/master/cantaloupe-variables.tf#L79

May actually need to be defined as: `CANTALOUPE_S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME`

I noticed this when my attempts to connect to an s3/minio bucket failed, and i found the following env var reference in your container image repo: https://github.com/UCLALibrary/docker-cantaloupe/blob/main/src/main/docker/configs/cantaloupe.properties.default-4.1.5#L207-L208

I have no way to test your terraform setup here, however making this change got things working for me. Thought I'd pass it on, just in case:

![image](https://user-images.githubusercontent.com/67506/93513239-6ccaa400-f8da-11ea-914e-4c44c92f997e.png)

**Comment by cachemeoutside** [comment]
Yes, the correct ENV to use is `CANTALOUPE_S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME`. We are using that in our terraform deployment. I was also tricked by the name scheme of the cache bucket ;)

https://github.com/UCLALibrary/ucla-aws-terraform-services/blob/master/environments/test/k8s/test-iiif/test-iiif.tfvars#L20

**Comment by ksclarke** [comment]
@cachemeoutside Do we need a PR to update https://github.com/UCLALibrary/terraform-kubernetes-cantaloupe/blob/master/cantaloupe-variables.tf#L79 (even though we're correctly overriding it elsewhere)? It might be helpful to others in the future that look here?
